version: '2'

services:
  mysql:
    image: aneh2killa/rpi-mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: very-strong-password
      MYSQL_DATABASE: data1
      MYSQL_USER: root
      MYSQL_PASSWORD: very-strong-password
      TZ: Asia/Kuala_Lumpur
    ports:
      - "3306:3306"

volumes:
  db_data:
